// vue-todo/src/components/NoteBook/components/BottomTool.vue
<template>
  <div class="bottom-tool-wrapper">
    <!-- 左边 -->
    <p class="section1">{{ getLeftItem(value)  }} item left</p>

    <!-- 中间 -->
    <section class="section2">
      <span :class="{ 'active': status === 'all' }" @click="$emit('book-all-click')">all</span>
      <span :class="{ 'active': status === 'active' }" @click="$emit('book-active-click')">active</span>
      <span :class="{ 'active': status === 'completed' }" @click="$emit('book-completed-click')">completed</span>
    </section>

    <!-- 右边 -->
    <p class="section3" @click="$emit('book-clear-completed-click')">clear completed</p>
  </div>
</template>

<script>
import { ENUM_NOTE_BOOK_STATUS } from '../enum'

export default {
  props: {
    value: {
      type: Array,
      default: () => []
    },
    status: {
      type: String
    }
  },
  computed: {
    getLeftItem (value) {
      return value => value.filter(item => item.status === ENUM_NOTE_BOOK_STATUS.ACTIVE).length
    }
  }
}
</script>

<style lang="scss" scoped>
  .bottom-tool-wrapper {
    cursor: pointer;
    font-size: 14px;
    padding: 15px 20px;
    color: rgb(77, 77, 77);
    border-top: 1px solid rgba(0, 0, 0, 0.06);
    display: grid;
    grid-template-columns: 100px 200px 100px;
    grid-template-areas: 'left center right';
    justify-content: space-between;
    .section1 {
      text-align: left;
    }
    .section2 {
      text-align: center;
      display: flex;
      justify-content: space-around;
      & .active {
        color: #67C23A;
      }
    }
    .section3 {
      text-align: right;
    }
  }
</style>

// react-todo/src/components/note-book/components/bottom-tool/index.js
import './index.css'
import React from 'react'
import { ENUM_NOTE_BOOK_STATUS } from '../../enum'

class BottomTool extends React.Component {
  constructor () {
    super()

    this.state = {}
  }
  
  render () {

    const getLeftItem = this.props.value.filter(item => item.status === ENUM_NOTE_BOOK_STATUS.ACTIVE).length

    return (
      <div className="bottom-tool-wrapper">
        {/* <!-- 左边 --> */}
        <p className="section1">{ getLeftItem } item left</p>

        {/* <!-- 中间 --> */}
        <section className="section2">
        <span className={ this.props.status === 'all' ? 'active' : null } onClick={ () => this.props.bookAll() }>all</span>
        <span className={ this.props.status === 'active' ? 'active' : null } onClick={ () => this.props.bookActive() }>active</span>
        <span className={ this.props.status === 'completed' ? 'active' : null } onClick={ () => this.props.bookCompleted() }>completed</span>
        </section>

        {/* <!-- 右边 --> */}
        <p className="section3" onClick={ () => this.props.bookClearCompleted() }>clear completed</p>          
      </div>
    )
  }
}

export default BottomTool
